config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'books#index'

  resources :books do
    resources :reviews
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews
  
  has_attached_file :book_img, :styles => { :book_index => "250x350>", :book_show => "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :find_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    if params[:category].blank?
      @books = Book.all.order("title ASC ")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @books = Book.where(:category_id => @category_id).order("title ASC")
    end
  end

  def new
    @book = current_user.books.build
    @categories = Category.all.map do |c|
      [c.name, c.id]
    end
  end

  def create
    @book = current_user.books.build(book_params)
    @book.category_id = params[:category_id]

    if @book.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    if @book.reviews.blank?
      @average_reviews = 0
    else
      @average_reviews = @book.reviews.average(:rating).round(2)
    end
  end

  def edit
    @categories = Category.all.map do |c|
      [c.name, c.id]
    end
  end

  def update
    @book.category_id = params[:category_id]
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private

    def book_params
      params.require(:book).permit(:title, :author, :description, :category_id, :book_img)
    end

    def find_book
      @book = Book.find(params[:id])
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.slim
.row
  .medium-6.medium-centered.large-4.large-centered.columns
    .row.column.log-in-form
      h4.text-center
        | Book Details
      br
      = simple_form_for @book, :html => { :multipart => true } do |f|
        = f.input :title
        = f.input :author
        = f.input :description
        = select_tag(:category_id, options_for_select(@categories), :prompt => "Select a Category")
        = f.file_field :book_img
        = f.button :submit

app/views/books/edit.html.slim
h2 
  | Edit Book
br  
  .row
    .medium-6.medium-centered.large-4.large-centered.columns
      .row.column.log-in-form
        h4.text-center
          | Book Details
        br
        = simple_form_for @book, :html => { :multipart => true } do |f|
          = f.input :title
          = f.input :author
          = f.input :description
          = f.select :category_id, @categories
          = f.file_field :book_img
          = f.button :submit

app/views/books/index.html.slim
h2
  | Book Index

h1.current-category
  = params[:category]
  
- if @books.count == 0
  h3
    | There are currently no books in this category. :(
- else
  .row
    - @books.each do |book|
      .small-6.large-3.columns
        a href="/books/#{book.id}" 
          = image_tag book.book_img.url(:book_index), class: "book"

app/views/books/new.html.slim
h2 
  | Add a New Book
br
  = render 'form'

app/views/books/show.html.slim
.row
  h2
    = @book.title
  br
  .medium-4.columns
    = image_tag @book.book_img.url(:book_show), class: "book-show"
    br
  .medium-8.columns
    h3
      = @book.author 
    br
    h4
      | Category: 
      = @book.category.name
    br
    h4
      | Average Rating
      .average-review-rating data-score="#{@average_reviews}"
    span
      | Based on #{@book.reviews.count} reviews
      br
    br
    p 
      = @book.description
br
.row
  .medium-4.columns
    h4
      | Reviews
    = render @book.reviews
    div
      = link_to "Add a Review for this book", new_book_review_path(@book) 
    
- if user_signed_in?
  - if @book.user_id == current_user.id 
    = link_to "Edit Book", edit_book_path(@book)  
    br
    = link_to "Delete Book", book_path(@book), method: :delete, data: { confirm: "Are you sure that you want to Delete this Book?" }
br
= link_to "Back", root_path

script
  |  $('.review-rating').raty({ readOnly: true, score: function() { return $(this).attr('data-score'); }, path: '/assets/' }); 
  
script
  |  $('.average-review-rating').raty({ readOnly: true, path: '/assets/', score: function() { return $(this).attr('data-score'); } });