config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'books#index'

  resources :books do
    resources :reviews
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.book_id = @book.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to book_path(@book)
  end

  private
    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_book
      @book = Book.find(params[:book_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.slim
.row
  .medium-6.medium-centered.large-4.large-centered.columns
    .row.column.log-in-form
      h4.text-center
        | Book Review
      br
      = simple_form_for([@book, @book.reviews.build]) do |f|
        .rating-form
          label
            | Rating 
            br
        = f.input :comment
        = f.button :submit

script
  | $('.rating-form').raty( { path: '/assets/', scoreName: 'review[rating]' } );

app/views/reviews/_review.html.slim
.review-rating data-score="#{review.rating}"
  |
p 
  = review.comment

- if user_signed_in?
  - if review.user_id = current_user.id
    = link_to "Edit", edit_book_review_path(review.book, review)
    br
    = link_to "Delete", book_review_path(review.book, review), method: :delete, data: { confirm: "Are You Sure?" } 
    br

app/views/reviews/edit.html.slim
h2 
  | Edit Review
br  
  .row
    .medium-6.medium-centered.large-4.large-centered.columns
      .row.column.log-in-form
        h4.text-center
          | Review Details
        br
        = simple_form_for([@book, @review]) do |f|
          .rating-form
            label
              | Rating 
              br
          = f.input :comment
          = f.button :submit

script
  | $('.rating-form').raty( { path: '/assets/', scoreName: 'review[rating]' } );

app/views/reviews/new.html.slim
h2 
  | Add a New Review
br
  = render 'form'