config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'books#index'

  resources :books do
    resources :reviews
  end
end

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      | BookReview
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link[href="/assets/favicon.ico" rel="shortcut icon" type="image/x-icon"]
  body
    .top-bar
      .top-bar-title
        span[data-responsive-toggle="responsive-menu" data-hide-for="medium"]
        strong#home_title
          = link_to "TheBookReviewer", root_path 
      #responsive-menu
        .top-bar-left
          ul.menu
            li
              = link_to "Sign Up", new_user_registration_path
            - if user_signed_in?
              li 
                = link_to "Sign Out", destroy_user_session_path, method: :delete
            - else
              li 
                = link_to "Log In", new_user_session_path
        .top-bar-right
          ul.menu
            li 
              ul.dropdown.menu[data-dropdown-menu]
                li
                  a
                    | Categories
                  ul.menu
                    - Category.all.each do |category|
                      li
                        = link_to category.name, books_path(category: category.name)
              - if user_signed_in?
                li
                  = link_to "Add New Book", new_book_path
                    
    p.notice 
      = notice
    p.alert
      = alert
    .row
      = yield

app/views/layouts/index.html.slim
h1
  | Welcome! Home Page